### ISSUE TITLE
Investigate praw 4.0

### ISSUE THREAD

**Issue by scowcron** [amici-ursi/ImagesOfNetwork#87]
Preliminary investigation needed. It's still in beta right now, but it might benefit both us and the praw maintainers if we pick it up. amici thinks that logging might becoming (OH YEAH!). also, it'll break everything we have. See just how much work it will take.

**Comment by 13steinj** [comment]
Emailing from mobile here:

Praw 4 for the most part is the same as praw3 it seems except for the
naming scheme-- the get_ prefix is removed from methods. Rate limiting is
improved as dynamic via the response headers rather than praw blocking the
thread with a time.sleep timeout. The authentication model and workflow has
changed, mostly for the better.

However beta is a bit of an understatement-- it shouldn't be used until at
least an actual release, many features that exist in praw3 aren't in praw4
as of yet due to the full rewrite. Don't particularly know how many would
or would not be needed.

**Comment by scowcron** [comment]
Also no `use logging`. Between these things, i'm going to go with no, at least for now.
